# Generated by Django 3.2.8 on 2021-10-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
